
# this is workflow name
name: Hello!

# runs on a trigger
on:
  # workflow_dispatch:
  push: 
    branches: [main]
    paths:
      - '**.html' 
  

# these are jobs inside the workflow
jobs: 
  # this is the name of job
  greet:
    # each job runs on a github runner
    runs-on: ubuntu-latest

    # steps to perform
    steps:
      - name: say hello to users
        run: echo "Hellow friends"

      - name: say hello to username
        run: echo "Hello $USER"

  tools_versions:
    runs-on: ubuntu-latest

    steps:
      - name: show what is the versiond of python, docker etc
        run: docker --version && python --version
        
  
        
        
